module.exports = {
    generalDir: "C:/Users/rober/Desktop/test/",
    dirSaveFile: {
        //ejemplo: "miruta/"
        bodega: "bodega/",
        clase_producto: "clase_producto/",
        conexion: "conexion/",
        control_sync: "control_sync/",
        cuenta_correntista: "cuenta_correntista/",
        cuenta_correntista_rel: "cuenta_correntista_rel/",
        cuenta_cta: "cuenta_cta/",
        cuenta_precio: "cuenta_precio/",
        cuenta_tipo_precio: "cuenta_tipo_precio/",
        dispositivo: "dispositivo/",
        empresa: "empresa/",
        error: "error/",
        impresora: "impresora/",
        inventario: "inventario/",
        precio: "precio/",
        producto: "producto/",
        producto_u_m: "producto_u_m/",
        s_doc_parametro: "s_doc_parametro/",
        s_doc_t_car_abo: "s_doc_t_car_abo/",
        s_doc_t_tra: "s_doc_t_tra/",
        serie_documento: "serie_documento/",
        serie_documento_user: "serie_documento_user/",
        tipo_cargo_abono: "tipo_cargo_abono/",
        tipo_documento: "tipo_documento/",
        tipo_transaccion: "tipo_transaccion/",
        unidad_medida: "unidad_medida/",
        user_bodega: "user_bodega/",
        usuario: "usuario/",
        nombresArchivo: "00.loadFilesData/"
    }
}